# Generated by Django 5.0.3 on 2024-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='media',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='images_dir',
            field=models.CharField(max_length=50),
        ),
    ]
