# Generated by Django 5.0.1 on 2024-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='card_holder',
        ),
        migrations.AddField(
            model_name='employeecard',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='holder_name',
            field=models.CharField(max_length=100),
        ),
    ]
