# Generated by Django 4.2.10 on 2024-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='message',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='card_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='personal_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='employer',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employerpassport',
            name='card_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='employerpassport',
            name='personal_number',
            field=models.CharField(max_length=14),
        ),
    ]
