# Generated by Django 4.2.10 on 2024-02-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0002_remove_job_image_remove_job_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAppeal',
            new_name='EmployeeReview',
        ),
        migrations.RenameModel(
            old_name='EmployerAppeal',
            new_name='EmployerReview',
        ),
    ]
