# Generated by Django 4.2.10 on 2024-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0002_alter_cv_media_alter_employeepassport_images_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeepassport',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeereview',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employerreview',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobappeal',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentappeal',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposals',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
