# Generated by Django 4.2.10 on 2024-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0003_category_data_time_cv_data_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepassport',
            name='images_dir',
            field=models.CharField(max_length=1000),
        ),
    ]
