# Generated by Django 5.0.1 on 2024-04-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page_app', '0004_alter_employeepassport_images_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='media',
        ),
        migrations.AddField(
            model_name='job',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='admin_page_app.employer'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeepassport',
            name='images_dir',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page_app.image'),
        ),
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_page_app.video'),
        ),
    ]
